export enum DeviceTypeEnum {
  PHOTOBOOTH = 'PHOTOBOOTH',
  PHOTOBOOTH_MINI = 'PHOTOBOOTH_MINI',
  MIRRORBOOTH = 'MIRRORBOOTH',
  MIRRORBOOTH_MINI = 'MIRRORBOOTH_MINI',
  VIDEOBOOTH = 'VIDEOBOOTH',
  AUDIOBOOTH = 'AUDIOBOOTH'
}
